### ISSUE TITLE
I nomi delle classi

### ISSUE THREAD

**Issue by mattmezza** [thedatasounds/crawler#1]
Ciao @AntonioCarletto 

https://github.com/thedatasounds/crawler/blob/master/src/main/java/io/datasounds/crawler/site1.java#L7

I nomi delle classi devo partire con una maiuscola e rispettare il camel case

**Comment by mattmezza** [comment]
quando risolvi commenta e chiudi la issue cosi capisco che è completata :-)

**Comment by AntonioCarletto** [comment]
I nomi delle classi site1, site2, site3 che non rispettavano il camel case sono state corrette.
