### ISSUE TITLE
I nomi dei metodi

### ISSUE THREAD

**Issue by mattmezza** [thedatasounds/crawler#2]
Ciao @AntonioCarletto 

https://github.com/thedatasounds/crawler/blob/master/src/main/java/io/datasounds/crawler/JobAdMicroHttp.java#L9

i nomi dei metodi devono partire con una minuscola e rispettare il camel case

**Comment by mattmezza** [comment]
quando risolvi commenta e chiudi la issue cosi capisco che è completata :-)

**Comment by AntonioCarletto** [comment]
Tutti i nomi dei metodi sono stati modificati secondo la caratteristica del camel case.
