### ISSUE TITLE
I nomi delle variabili

### ISSUE THREAD

**Issue by mattmezza** [thedatasounds/crawler#3]
Ciao @AntonioCarletto 

https://github.com/thedatasounds/crawler/blob/master/src/main/java/io/datasounds/crawler/App.java#L9

i nomi delle variabili devono partire con una minuscola e rispettare il camel case. Sono nel caso in cui si tratti di variabili statiche (o di classe) lo standard prevede la scrittura tutta in maiuscolo in snake case (ad es. VARIABILE_STATICA = 'valore')

**Comment by mattmezza** [comment]
quando risolvi commenta e chiudi la issue cosi capisco che è completata :-)

**Comment by AntonioCarletto** [comment]
I nomi delle variabili sono state corrette.
