### ISSUE TITLE
evitare ripetizioni di stringhe

### ISSUE THREAD

**Issue by mattmezza** [thedatasounds/crawler#4]
Onde evitare stupidi errori, creati delle variabili statiche finali pubbliche in Factory Producer che poi utilizzerai dappertutto per il settaggio e per il confronto.

**Comment by mattmezza** [comment]
quando risolvi commenta e chiudi la issue cosi capisco che è completata :-)

**Comment by AntonioCarletto** [comment]
Variabili final create.
