### ISSUE TITLE
Mai restituire null

### ISSUE THREAD

**Issue by mattmezza** [thedatasounds/crawler#5]
È sempre buona norma mai restituire null per evitare i NullPointerException. Al posto di restituire null lancia un'eccezione che verrà catturata a livello superiore.

**Comment by mattmezza** [comment]
quando risolvi commenta e chiudi la issue cosi capisco che è completata :-)

**Comment by AntonioCarletto** [comment]
Inserita alla fine di tutte le classi che restituivano un puntatore a null, un'eccezione throw new exception(""); quando non restituisce il risultato voluto. Cambiate anche i tipi per la classe printAd() da String a Sting[][].
